// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/envolope.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoblinStream_Communicate_FullMethodName = "/proto.GoblinStream/Communicate"
)

// GoblinStreamClient is the client API for GoblinStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoblinStreamClient interface {
	Communicate(ctx context.Context, opts ...grpc.CallOption) (GoblinStream_CommunicateClient, error)
}

type goblinStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewGoblinStreamClient(cc grpc.ClientConnInterface) GoblinStreamClient {
	return &goblinStreamClient{cc}
}

func (c *goblinStreamClient) Communicate(ctx context.Context, opts ...grpc.CallOption) (GoblinStream_CommunicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &GoblinStream_ServiceDesc.Streams[0], GoblinStream_Communicate_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &goblinStreamCommunicateClient{stream}
	return x, nil
}

type GoblinStream_CommunicateClient interface {
	Send(*Envelope) error
	Recv() (*Envelope, error)
	grpc.ClientStream
}

type goblinStreamCommunicateClient struct {
	grpc.ClientStream
}

func (x *goblinStreamCommunicateClient) Send(m *Envelope) error {
	return x.ClientStream.SendMsg(m)
}

func (x *goblinStreamCommunicateClient) Recv() (*Envelope, error) {
	m := new(Envelope)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GoblinStreamServer is the server API for GoblinStream service.
// All implementations must embed UnimplementedGoblinStreamServer
// for forward compatibility
type GoblinStreamServer interface {
	Communicate(GoblinStream_CommunicateServer) error
	mustEmbedUnimplementedGoblinStreamServer()
}

// UnimplementedGoblinStreamServer must be embedded to have forward compatible implementations.
type UnimplementedGoblinStreamServer struct {
}

func (UnimplementedGoblinStreamServer) Communicate(GoblinStream_CommunicateServer) error {
	return status.Errorf(codes.Unimplemented, "method Communicate not implemented")
}
func (UnimplementedGoblinStreamServer) mustEmbedUnimplementedGoblinStreamServer() {}

// UnsafeGoblinStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoblinStreamServer will
// result in compilation errors.
type UnsafeGoblinStreamServer interface {
	mustEmbedUnimplementedGoblinStreamServer()
}

func RegisterGoblinStreamServer(s grpc.ServiceRegistrar, srv GoblinStreamServer) {
	s.RegisterService(&GoblinStream_ServiceDesc, srv)
}

func _GoblinStream_Communicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoblinStreamServer).Communicate(&goblinStreamCommunicateServer{stream})
}

type GoblinStream_CommunicateServer interface {
	Send(*Envelope) error
	Recv() (*Envelope, error)
	grpc.ServerStream
}

type goblinStreamCommunicateServer struct {
	grpc.ServerStream
}

func (x *goblinStreamCommunicateServer) Send(m *Envelope) error {
	return x.ServerStream.SendMsg(m)
}

func (x *goblinStreamCommunicateServer) Recv() (*Envelope, error) {
	m := new(Envelope)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GoblinStream_ServiceDesc is the grpc.ServiceDesc for GoblinStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoblinStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GoblinStream",
	HandlerType: (*GoblinStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communicate",
			Handler:       _GoblinStream_Communicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/envolope.proto",
}
