// Copyright (c) 2025 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

//go:build mage
// +build mage

package main

import (
	"debug/elf"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/goppydae/magelib/pkg/magelib"
	"github.com/magefile/mage/mg"
	"github.com/magefile/mage/sh"
	"github.com/zeebo/blake3"
)

// toolchain is this repo's single declaration of what the dev shell must
// provide. Doctor reports on it and checkHermetic gates on it, so the
// advisory check and the enforcing one read one value and cannot drift:
// MAGELIB-DIV-003 is exactly the drift that two declarations produce.
var toolchain = magelib.DoctorConfig{
	ReplaceTargets: []string{"../magelib"},
	ProtoPlugins:   []string{"buf", "protoc-gen-go", "protoc-gen-go-grpc"},
	GopyVersion:    "v0.4.10",
	RequiredEnv:    []string{"GOBIN"},
	// gopy joined this list when it stopped being built by the shell hook
	// and started coming from the flake (GAPI-DIV-096). It earns its place
	// here rather than only in the binding-toolchain check because that
	// check asks whether gopy is PRESENT at the pinned version, and this
	// one asks where it came FROM. The old hook installed it into
	// $GOBIN=.bin, which leads PATH and is not under /nix/store, so
	// reintroducing that build makes hermetic-resolution fail - in doctor
	// and in checkHermetic, which gates every real target.
	// hugo replaced mkdocs and pandoc when the generated site landed. All
	// three are documentation tools and that is the whole resemblance:
	// mkdocs rendered a hand-written tree that nothing generated, and
	// pandoc converted three of those pages into man pages that nothing
	// compared to source. Both targets are retired, so leaving their
	// tools declared would have kept two entries the doctor requires,
	// the hermetic check gates on, and no target uses.
	SharedTools: []string{"buf", "golangci-lint", "gosec", "govulncheck", "mage", "goimports", "hugo", "gopy"},
}

// fileLengthWaivers is DEBT: hand-written files the 500-line rule applies
// to and that violate it today. The gate measures every one of them, and
// it FAILS once a file comes back at or under the limit, naming the
// waiver to delete - so this list can only ever shrink. Adding a line to
// this list is a decision to carry a violation, not to exempt a file.
//
// Line counts when the gate landed, for anyone judging progress:
// python_agent.go 816, go_agent.go 730, tui.go 603, discovery.go 560,
// go_agent_test.go 539. Test files count; the manifesto exempts
// generated, vendored and data files, and a _test.go file is none of
// those.
// Magefile.go joined this list on 2026-08-02 at 518 lines, the first
// addition since the gate landed. It sat at 496 - four lines under -
// so it could not accept a target of any size: a bare three-line
// function plus a blank line lands exactly on 500, and the rule is
// LESS THAN 500. Adding CheckVersion for MAGELIB-DIV-006 was the change
// that made the ceiling load-bearing.
//
// Operator decision, 2026-08-02: carry it as debt rather than split the
// targets across a second build-tagged file. mage reads every such file
// in the directory, so a split would have worked and passed with no
// waiver at all; the call is that one discoverable Magefile is worth
// more than a clean waiver list. The exit is to shorten this file, not
// to grow the list.
var fileLengthWaivers = []string{
	"Magefile.go",
	"core/agentmgr/python_agent.go",
	"core/agentmgr/go_agent.go",
	"core/tui/tui.go",
	"core/agentmgr/discovery.go",
	"core/agentmgr/go_agent_test.go",
}

// fileLengthSkips is EXEMPTION, not debt: paths the 500-line rule does
// not reach at all. They are never measured, so they are never reported
// and never expected to shrink. A path may be a waiver or a skip, never
// both; the gate rejects claiming both as a config error.
//
// The entry below must NOT be a waiver: at 1312 lines gopy's output can
// never come under the limit, so it would sit in the waiver list
// forever, undeletable and indistinguishable from the five real
// violations that are supposed to disappear. Why the rule does not
// reach it is stated in the Reason, where a reviewer can audit the
// claim rather than take this comment's word for it.
var fileLengthSkips = []magelib.Skip{
	{
		Name: "adk/python/gapi/native",
		Reason: "gopy output: adk.go is regenerated by Python{}.Build and never " +
			"hand-edited, but gopy stamps \"File is generated by gopy. Do not " +
			"edit.\" in a block comment, which magelib's standard " +
			"\"// Code generated ... DO NOT EDIT.\" marker does not match - so " +
			"the manifesto's generated-code exemption must be declared by hand.",
	},
}

// licenseNotice is gapi's declaration for the MPL header gate: a holder
// and a year, and deliberately nothing else. The Exhibit A prose and the
// SPDX line live in magelib and are never spelled here, which is the
// lesson the terminology gate paid for - moving that gate into the
// library moved the LOGIC while each consumer kept declaring the
// literals in the Magefile the gate itself walks.
//
// Year is 2025, gapi's year of FIRST PUBLICATION, and it does not
// advance. A file added in 2027 still carries 2025: per-file current
// years would force the gate to accept any year, at which point it
// stops discriminating. Per-repo years are gapi 2025, goblin 2025,
// magelib 2026, goppydae-docs 2026 (operator decision 16).
var licenseNotice = magelib.LicenseConfig{
	Holder: "Steven Verhelle (enqack)",
	Year:   2025,
}

// licenseSkips is EXEMPTION, not debt, and it names the same directory
// as fileLengthSkips above for a related but DISTINCT reason.
//
// Generated code gets no per-file header (operator decision 19): a
// hand-maintained notice there is wiped by the next regeneration, so
// each repo's LICENSE carries a paragraph covering generated artifacts
// instead. magelib's gate already exempts generated files by itself,
// so almost nothing needs declaring - but it detects them by the
// standard "// Code generated ... DO NOT EDIT." marker in the leading
// comment block, and gopy's output matches that in NEITHER respect.
//
// MEASURED 2026-08-04, both failure modes at once, which is why this
// cannot be left to the automatic detector:
//
//   - adk.go carries gopy's marker inside a /* */ BLOCK comment, so the
//     scan reaches a line that is not "//" and concludes it has hit
//     code before it ever sees the marker.
//   - adk.py, go.py and build.py are "#"-commented, and the marker
//     regexp only recognises "//" - so a hash-commented generated file
//     is structurally undetectable, not merely unmatched.
//
// One directory skip covers all five files, __init__.py included.
// Without it the sweep headers output that Python{}.Build regenerates,
// and the notice silently disappears on the next build.
var licenseSkips = []magelib.Skip{
	{
		Name: "adk/python/gapi/native",
		Reason: "gopy output, regenerated by Python{}.Build and never hand-edited: " +
			"the .go file marks itself generated inside a block comment and the " +
			".py files do so with hash comments, neither of which magelib's " +
			"generated-file detector recognises, so the decision-19 exemption " +
			"must be declared by hand.",
	},
}

// versionLdflags stamps the resolved version into core/version, the shared
// injection point read by both binaries (VERSION file is the source of truth).
//
// IT STAMPS ONLY WHAT THIS BUILD PATH CAN SUPPLY THAT THE BINARY CANNOT
// DERIVE (GAPI-DIV-126). A mage build runs in a git checkout, so
// vcs.revision and vcs.time are recorded in the binary's build info for
// free and core/version reads them - stamping Commit and Source Date
// here would add two hand-maintained ldflags that can drift from the
// module actually built, which is the defect class MAGELIB-DIV-006 spent
// a release closing. The nix derivation stamps both because it has no
// repository to read.
//
// What only the build knows: which tool ran it, and whether the ref is a
// release.
func versionLdflags() string {
	const pkg = "github.com/goppydae/gapi/core/version."
	return strings.Join([]string{
		"-X " + pkg + "GAPIVersion=" + magelib.Version(),
		"-X " + pkg + "BuiltBy=mage",
		"-X " + pkg + "BuildTag=" + buildChannel(),
	}, " ")
}

// buildChannel is the build channel: `release` from a tag ref, `dev`
// otherwise (cli-contract.md).
//
// Recorded because Build Tag had no definition when GAPI-DIV-126 was
// filed, and a field whose semantics nobody can state cannot be given a
// correct value. The ref variables are the ones the forge sets and the
// ones release-guard already reads, so a local build is `dev` by
// construction rather than by a check that could be forgotten.
func buildChannel() string {
	if os.Getenv("GITHUB_REF_TYPE") == "tag" {
		return "release"
	}
	return "dev"
}

func Build() error {
	mg.Deps(checkHermetic)
	fmt.Printf("Building gapid and gapictl (version %s)...\n", magelib.Version())

	if err := sh.Run("go", "build", "-ldflags", versionLdflags(), "-o", "bin/gapid", "./cmd/gapid"); err != nil {
		return err
	}

	if err := sh.Run("go", "build", "-ldflags", versionLdflags(), "-o", "bin/gapictl", "./cmd/gapictl"); err != nil {
		return err
	}

	// Calculate and write BLAKE3 hashes
	for _, bin := range []string{"bin/gapid", "bin/gapictl"} {
		if err := hashFile(bin); err != nil {
			return fmt.Errorf("hashing %s failed: %w", bin, err)
		}
	}

	fmt.Println("Build complete: bin/gapid, bin/gapictl (with .b3 checksums)")
	return nil
}

func hashFile(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	h := blake3.New()
	if _, err := io.Copy(h, f); err != nil {
		return err
	}

	sum := h.Sum(nil)
	hexSum := hex.EncodeToString(sum)

	return os.WriteFile(path+".b3", []byte(hexSum+"\n"), 0644)
}

func Install() error {
	mg.Deps(checkHermetic)
	fmt.Println("Installing gapid and gapictl...")

	if err := sh.Run("go", "install", "-ldflags", versionLdflags(), "./cmd/gapid"); err != nil {
		return err
	}

	if err := sh.Run("go", "install", "-ldflags", versionLdflags(), "./cmd/gapictl"); err != nil {
		return err
	}

	fmt.Println("Installed to $GOPATH/bin")
	return nil
}

// Test runs all tests with the race detector (the suite CI runs)
func Test() error {
	mg.Deps(checkHermetic)
	fmt.Println("Running tests (-race)...")
	return sh.RunV("go", "test", "-race", "./...")
}

// TestShort runs the fast inner-loop subset
func TestShort() error {
	mg.Deps(checkHermetic)
	fmt.Println("Running short tests...")
	return sh.RunV("go", "test", "-short", "./...")
}

// Fuzz runs every Fuzz* target for a bounded fuzztime
func Fuzz() error {
	mg.Deps(checkHermetic)
	return magelib.FuzzAll("10s")
}

// Vuln runs govulncheck (named offline exception: skipped loudly when offline)
func Vuln() error {
	mg.Deps(checkHermetic)
	return magelib.Vuln()
}

// Doctor validates the local environment against the ecosystem pins
func Doctor() error {
	return magelib.Doctor(toolchain)
}

// CheckVersion gates the VERSION file against the tag being cut.
//
// Invoked by release-guard.yml on a tag ref, and by the operator before
// cutting one, which is the only form that PREVENTS rather than detects:
//
//	GITHUB_REF_TYPE=tag GITHUB_REF_NAME=v0.1.0-proto2g mage checkVersion
//
// Deliberately not a dependency of Lint or Build. It errors off a tag
// ref by design, so wiring it into a target that runs on every pull
// request would make it permanently red or - the likelier repair -
// silence it into the no-op it must never become. See MAGELIB-DIV-006.
//
// gapi has a second reader of VERSION that magelib lacks:
// nix/package.nix takes lib.fileContents ../VERSION with no ref-name
// fallback, for both the store path and the core/version.GAPIVersion
// ldflag, so a missed bump also shows up as a wrongly-named derivation.
// Nothing asserts those two readers stay in agreement; that residual is
// recorded on MAGELIB-DIV-006.
func CheckVersion() error {
	return magelib.CheckVersionAgainstTag()
}

// EnvCheck compares the sibling dev shells' tool inventories; skew is red
func EnvCheck() error {
	return magelib.CheckShellUnification(
		map[string]string{"gapi": ".", "goblin": "../goblin", "magelib": "path:../magelib"},
		[]string{
			"go", "gcc", "protoc",
			// THE CODEGEN PLUGINS, and they are the reason this list grew
			// (MAGELIB-DIV-010 blind spot 2). They were in all three flakes
			// and in no unification check, so nothing asserted the shells
			// resolve the SAME protoc-gen-go. For a codegen plugin a
			// store-path difference is not cosmetic: it produces different
			// generated output from identical .proto files.
			"protoc-gen-go", "protoc-gen-go-grpc",
			"buf", "golangci-lint", "gosec", "govulncheck",
			"mage", "goimports",
		},
	)
}

// TestUnit runs only unit tests
func TestUnit() error {
	mg.Deps(checkHermetic)
	fmt.Println("Running unit tests...")
	return sh.RunV("go", "test", "-v", "./internal/...")
}

// TestADK runs ADK integration tests
func TestADK() error {
	mg.Deps(Build, Python{}.Build)
	fmt.Println("Running ADK integration tests...")
	return sh.RunV("go", "test", "-v", "./test/adk/...")
}

// TestPid1 runs the PID-1 container e2e: gapid as init of a rootless
// podman container (orphan reaping, signal semantics, teardown order).
func TestPid1() error {
	mg.Deps(checkHermetic)
	fmt.Println("Running PID-1 container e2e (rootless podman)...")
	return sh.RunV("go", "test", "-tags", "pid1", "-timeout", "10m", "-v", "-run", "TestPid1", "./test/pid1/")
}

// TestE2E runs end-to-end tests
func TestE2E() error {
	mg.Deps(Build, Python{}.Build)
	fmt.Println("Running E2E tests...")
	return sh.RunV("./test/e2e.sh")
}

// TestIntegrity runs integrity verification tests
func TestIntegrity() error {
	mg.Deps(Build)
	fmt.Println("Running integrity tests...")
	return sh.RunV("./test/test_integrity.sh")
}

// TestTimer runs timer agent tests
func TestTimer() error {
	mg.Deps(Build, Python{}.Build)
	fmt.Println("Running timer tests...")
	return sh.RunV("./test/test_timer.sh")
}

// Release cross-compiles pure-Go release artifacts (CGO_ENABLED=0) for
// linux/{amd64,arm64} and darwin/{amd64,arm64} into dist/, with a SHA256SUMS
// manifest. Signing (minisign) and the signed tag are operator-gated and
// printed as a stub.
func Release() error {
	mg.Deps(checkHermetic)
	return magelib.Release("gapi", "dist", versionLdflags(), map[string]string{
		"gapid":   "./cmd/gapid",
		"gapictl": "./cmd/gapictl",
	})
}

// Clean removes build artifacts
func Clean() error {
	fmt.Println("Cleaning build artifacts...")

	dirs := []string{"bin", "build", "dist"}
	for _, dir := range dirs {
		if err := sh.Rm(dir); err != nil {
			fmt.Printf("Warning: failed to remove %s: %v\n", dir, err)
		}
	}

	fmt.Println("Clean complete")
	return nil
}

// Proto generates protobuf code through the buf gate (generate, lint,
// breaking). Generated code lands directly in pkg/proto (buf.gen.yaml
// module opt strips the module prefix from go_package).
func Proto() error {
	mg.Deps(checkHermetic)
	// ".git#ref=HEAD" compares an edited working tree against the last
	// commit, which is right for a developer and inert in CI, where the
	// working tree IS the commit and the schema would be compared
	// against itself. CI names its own baseline - the pull request's
	// merge base - through PROTO_BREAKING_AGAINST, which magelib reads
	// and which supersedes this value.
	if err := magelib.BufGenerate(".git#ref=HEAD"); err != nil {
		return err
	}
	fmt.Println("Protobuf generation complete (buf generate + lint + breaking)")
	return nil
}

// Fmt formats all Go code
func Fmt() error {
	return magelib.Fmt()
}

// Lint runs linters.
//
// Rule-level gosec carve-outs (GAPI-DIV-024):
//   - G204: gapid is a process supervisor; launching operator-registered
//     agent binaries and interpreters with discovered paths is the product.
//     Discovery roots are fenced (GAPI_AGENT_PATH) and binaries are
//     signature-verified before start (agentreg integrity check).
//   - G304: every variable-path open routes through internal/safeio, the
//     audited chokepoint (clean + absolute, root-confined where a root
//     exists); the rule now only fires inside that package.
func Lint() error {
	mg.Deps(checkHermetic, checkTerminology, checkFileLength, checkLedger, LicenseCheck, Docs.Check, checkDocsLocation)
	return magelib.Lint("G204", "G304")
}

// LicenseCheck reports every hand-written file missing the MPL notice.
//
// A dependency of Lint as of the sweep that headered this repo, which
// is the sequencing the license plan requires: wiring it BEFORE the
// sweep would have turned every CI run red, and CI minutes are the
// scarce resource the whole licence effort exists to obtain. Sweep and
// gate land together so the gate is never a mechanism with no caller.
func LicenseCheck() error {
	return magelib.CheckLicenseHeaders(licenseNotice, licenseSkips...)
}

// LicenseAdd inserts the notice into every file LicenseCheck reports.
//
// AddLicenseHeaders PRINTS each modified path and the total itself, so
// the returned slice is discarded here rather than printed again. That
// list is the point, not a convenience: it is what the `git add` line
// is built from. This repo's sweep touched 226 files at once, in a
// silo other sessions edit concurrently, and `git add -A` is banned
// twice over precisely here.
func LicenseAdd() error {
	_, err := magelib.AddLicenseHeaders(licenseNotice, licenseSkips...)
	return err
}

// Tidy runs go mod tidy
func Tidy() error {
	return magelib.Tidy()
}

// Dev runs the development build and starts gapid
func Dev() error {
	mg.Deps(Build, Python{}.Build)
	fmt.Println("Starting gapid in development mode...")
	return sh.RunV("./bin/gapid", "start")
}

// All runs fmt, tidy, build, and test
func All() error {
	mg.Deps(Fmt, Tidy, Build, Test)
	fmt.Println("All tasks complete")
	return nil
}

// CI reproduces ci.yml's pull-request jobs locally, in CI's order.
//
// NOT `All`. All runs Fmt and Tidy, which REPAIR the tree, so it cannot
// fail the way CI fails: an unformatted file is fixed by All and
// REJECTED by lint. An audit against the workflows found All covering
// two of the sixteen things CI runs.
func CI() error {
	return magelib.RunCI(magelib.CIConfig{
		Steps: []magelib.Step{
			// Environment first. A wrong toolchain makes every result
			// below meaningless rather than wrong.
			magelib.Target("doctor", Doctor),
			magelib.Target("envcheck", EnvCheck),
			magelib.Target("lint", Lint),

			magelib.Target("build", Build),
			magelib.Target("vuln", Vuln),

			// python:build before anything that loads the binding, or
			// the suites run against a stub and pass.
			magelib.Target("python:build", Python{}.Build),
			magelib.Target("test", Test),
			magelib.Target("testIntegrity", TestIntegrity),
			magelib.Target("testTimer", TestTimer),

			magelib.Cmd("cross-ADK parity", "go", "test", "-v", "./test/adk/",
				"-run", "TestCrossADKParity|TestADKIntegration"),

			// Regenerating proves the generator runs; only the diff
			// proves the COMMITTED output is what the pinned plugins
			// produce. The baseline matters as much: Proto's own default
			// compares the tree against itself and can never fail.
			magelib.Step{Name: "proto (breaking against the merge base)", Run: func() error {
				if err := magelib.WithProtoBaseline(magelib.ProtoBaseline(), Proto); err != nil {
					return err
				}
				return magelib.AssertClean("pkg/proto")
			}},

			magelib.Step{Name: "nix build", Run: func() error { return magelib.NixBuild(".#") }},
			magelib.Step{Name: "nix flake check --all-systems", Run: magelib.NixFlakeCheckAllSystems},
		},
		Excluded: []string{
			"No-Replace Module Resolution - runs `rm -rf vendor` and resolves " +
				"from the module proxy under a read token; this repo COMMITS vendor/",
			"VM Checks - deliberately off the pull-request path (vm-checks.yml); " +
				"run `mage ciVM`",
			"release-guard checkVersion - fires on a tag push, not a pull request",
		},
	})
}

// CIVM runs vm-checks.yml: the guest-booting gate, which needs KVM and
// minutes and is deliberately NOT on the pull-request path.
func CIVM() error {
	return sh.RunV("nix", "flake", "check", "--print-build-logs",
		"--max-jobs", "1", "--keep-going")
}

// docsConfig is this repo's documentation site.
//
// Generators is what gives tools/gendocs a caller. Until this landed
// nothing in the Magefile, any workflow or any nix file invoked it, so
// the 28 CLI pages, 30 man pages, configuration reference and
// defaults.json on main were generated once and committed with NOTHING
// comparing them to source - worse than not generating at all, because
// the output looks generated. See GAPI-DIV-119.
//
// The generator is invoked with ONE APPENDED ARGUMENT, the output root.
// That is magelib's contract and it is what makes the drift gate
// trustworthy: CheckDocsDrift regenerates into a temporary tree and
// byte-compares, which it can only do if generation is redirectable. A
// generator that hardcoded its output would force the gate to either
// mutate the working tree - repairing the drift it is measuring - or
// compare against something it did not produce.
//
// APIPackages is empty, so no gomarkdoc target exists here. gapi
// publishes an operator reference rather than a Go API reference; the
// exported surface is served by pkg.go.dev, which the sidebar links.
//
// Committed names all 60 generated paths individually because the gate's
// third condition depends on it: a file that generation produces and
// Committed does not name is reported as UNTRACKED, so an artifact
// cannot quietly fall outside drift control. Listing a directory would
// give up exactly that check.
var docsConfig = magelib.DocsConfig{
	Dir:        "docs",
	Title:      "gapi",
	BaseURL:    "https://goppydae.github.io/gapi/",
	Repo:       "github.com/goppydae/gapi",
	Generators: [][]string{{"go", "run", "./tools/gendocs"}},
	Committed:  docsCommitted,
	// MAGELIB-DIV-016's exit names THIS sidebar as one of its two
	// closing halves: the hub must lose the pkg.go.dev link and gapi
	// must keep it, because a change that removed it everywhere would
	// satisfy the first and quietly break the second. Making the
	// element opt-in did exactly that - no consumer opted in - so gapi
	// carried no link at all. github.com/goppydae/gapi serves 200 on
	// pkg.go.dev now that operator decision 24 has published the repo,
	// measured 2026-08-08.
	ImportableModule: true,
}

// docsCommitted are the generated paths under drift control.
//
// Every path here is produced by tools/gendocs and checked in, so the
// reference is readable on the forge without a build. The list is
// exhaustive by necessity rather than by style: CheckDocsDrift reports
// a generated file this list omits as untracked and fails, which is the
// condition that keeps a new page from escaping the gate.
var docsCommitted = []string{
	// The gapictl and gapid command trees, walked from the roots the
	// binaries actually run.
	"docs/content/reference/cli/gapictl/gapictl.md",
	"docs/content/reference/cli/gapictl/gapictl_agent.md",
	"docs/content/reference/cli/gapictl/gapictl_agent_build.md",
	"docs/content/reference/cli/gapictl/gapictl_agent_clean.md",
	"docs/content/reference/cli/gapictl/gapictl_agent_new.md",
	"docs/content/reference/cli/gapictl/gapictl_agent_reload.md",
	"docs/content/reference/cli/gapictl/gapictl_agent_status.md",
	"docs/content/reference/cli/gapictl/gapictl_agent_verify.md",
	"docs/content/reference/cli/gapictl/gapictl_crypto.md",
	"docs/content/reference/cli/gapictl/gapictl_crypto_age-keygen.md",
	"docs/content/reference/cli/gapictl/gapictl_crypto_decrypt.md",
	"docs/content/reference/cli/gapictl/gapictl_crypto_encrypt.md",
	"docs/content/reference/cli/gapictl/gapictl_crypto_keygen.md",
	"docs/content/reference/cli/gapictl/gapictl_crypto_sign.md",
	"docs/content/reference/cli/gapictl/gapictl_crypto_verify.md",
	"docs/content/reference/cli/gapictl/gapictl_lifecycle.md",
	"docs/content/reference/cli/gapictl/gapictl_lifecycle_reload.md",
	"docs/content/reference/cli/gapictl/gapictl_lifecycle_restart.md",
	"docs/content/reference/cli/gapictl/gapictl_lifecycle_start.md",
	"docs/content/reference/cli/gapictl/gapictl_lifecycle_status.md",
	"docs/content/reference/cli/gapictl/gapictl_lifecycle_stop.md",
	"docs/content/reference/cli/gapictl/gapictl_ping.md",
	"docs/content/reference/cli/gapictl/gapictl_shutdown.md",
	"docs/content/reference/cli/gapictl/gapictl_tui.md",
	"docs/content/reference/cli/gapictl/gapictl_version.md",
	"docs/content/reference/cli/gapid/gapid.md",
	"docs/content/reference/cli/gapid/gapid_start.md",
	"docs/content/reference/cli/gapid/gapid_version.md",

	// The configuration reference, a join of the registered defaults
	// and a reflection walk over the config schema.
	"docs/content/reference/configuration.md",

	// Man pages: sections 1 and 5 generated from the same sources as
	// the pages above, section 7 converted from the written overview.
	"docs/man/man1/gapictl-agent-build.1",
	"docs/man/man1/gapictl-agent-clean.1",
	"docs/man/man1/gapictl-agent-new.1",
	"docs/man/man1/gapictl-agent-reload.1",
	"docs/man/man1/gapictl-agent-status.1",
	"docs/man/man1/gapictl-agent-verify.1",
	"docs/man/man1/gapictl-agent.1",
	"docs/man/man1/gapictl-crypto-age-keygen.1",
	"docs/man/man1/gapictl-crypto-decrypt.1",
	"docs/man/man1/gapictl-crypto-encrypt.1",
	"docs/man/man1/gapictl-crypto-keygen.1",
	"docs/man/man1/gapictl-crypto-sign.1",
	"docs/man/man1/gapictl-crypto-verify.1",
	"docs/man/man1/gapictl-crypto.1",
	"docs/man/man1/gapictl-lifecycle-reload.1",
	"docs/man/man1/gapictl-lifecycle-restart.1",
	"docs/man/man1/gapictl-lifecycle-start.1",
	"docs/man/man1/gapictl-lifecycle-status.1",
	"docs/man/man1/gapictl-lifecycle-stop.1",
	"docs/man/man1/gapictl-lifecycle.1",
	"docs/man/man1/gapictl-ping.1",
	"docs/man/man1/gapictl-shutdown.1",
	"docs/man/man1/gapictl-tui.1",
	"docs/man/man1/gapictl-version.1",
	"docs/man/man1/gapictl.1",
	"docs/man/man1/gapid-start.1",
	"docs/man/man1/gapid-version.1",
	"docs/man/man1/gapid.1",
	"docs/man/man5/gapi.conf.5",
	"docs/man/man7/gapi.7",

	// The defaults, published as data so a document can cite a value
	// without transcribing it.
	"docs/data/defaults.json",
}

// Documentation tasks
type Docs mg.Namespace

// Sync materialises the shared Hugo assets into docs/.magelib.
func (Docs) Sync() error {
	mg.Deps(checkHermetic)
	return magelib.DocsSync(docsConfig)
}

// Generate renders the reference from source.
func (Docs) Generate() error {
	mg.Deps(checkHermetic)
	return magelib.DocsGenerate(docsConfig)
}

// Build renders the static site into docs/public.
func (Docs) Build() error {
	mg.Deps(checkHermetic)
	return magelib.DocsBuild(docsConfig)
}

// Serve runs Hugo's own server with live reload.
func (Docs) Serve() error {
	mg.Deps(checkHermetic)
	return magelib.DocsServe(docsConfig)
}

// Check runs every documentation gate.
//
// Wired into Lint rather than left to a separate invocation, because a
// gate nobody runs is the state this repo's reference was already in.
//
// ONE CALL RATHER THAN A LIST THAT DRIFTS. This was CheckDocsDrift
// alone, so MAGELIB-DIV-012's rendered-h1 gate and -013's advertised-
// taxonomy gate shipped in magelib v0.9.0 and ran nowhere here - the
// silo's dominant defect shape, a mechanism built and never wired.
// CheckDocs composes all three, so a gate magelib adds next reaches
// this repo with the re-vendor instead of waiting for somebody to
// remember a second line.
func (Docs) Check() error {
	mg.Deps(checkHermetic)
	return magelib.CheckDocs(docsConfig)
}

// checkHermetic ensures tools are running from Nix store
func checkHermetic() error {
	return magelib.CheckHermetic(toolchain.SharedTools...)
}

// checkHermeticPython gates the Python extension build on the tools THAT
// TARGET RUNS, rather than on the repo-wide set.
//
// GAPI-DIV-085: the derivation has to build the extension wherever it
// installs the runner, and decision 35 says it does that by calling
// `mage python:build` rather than reimplementing its four steps in Nix -
// because the invariant lived in one place and was still wrong for
// months, and two places is worse. The obstacle was this gate: inheriting
// SharedTools made building a C extension require mkdocs, pandoc, gosec,
// golangci-lint and buf to be present, so satisfying it in a sandbox
// meant making a documentation toolchain a build input of the package.
//
// Narrowing it is not a weakening. A gate that demands tools its target
// never executes is not asserting hermeticity, it is asserting that you
// are standing in the dev shell - a different and weaker claim, since it
// passes for a target whose actual tools came from somewhere else. These
// four are what python:build execs; magelib adds go, gcc and protoc.
func checkHermeticPython() error {
	return magelib.CheckHermetic("gopy", "goimports")
}

// checkTerminology enforces the silo's naming rules through magelib.
// The rules themselves live there, not here: a Magefile sits at the
// repo root and is walked, so declaring the phrases inline would trip
// the gate on its own declaration.
//
// The two ledgers are skipped; each skip states its own reason at the
// call below, which is where a reviewer can audit the claim.
func checkTerminology() error {
	return magelib.CheckTerminology(magelib.GoppydaeTerminologyRules,
		magelib.Skip{
			Name: "divergence.jsonl",
			Reason: "the divergence ledger quotes the phrases it polices: " +
				"GAPI-DIV-044 is the entry that fixes GAPI's expansion and the " +
				"styling of the product name, and it cannot record either " +
				"decision without writing the rejected spelling down. Both of " +
				"the gate's rules match that one line, so the gate would go red " +
				"against the entry that asked for it.",
		},
		magelib.Skip{
			Name: "deprecation.jsonl",
			Reason: "the deprecation ledger is the sibling surface of the same " +
				"exemption: retiring a name means writing the retired name down, " +
				"so an entry deprecating a term must quote it. Zero lines match " +
				"today (both rules, checked 2026-08-01) - the skip is granted " +
				"for the record it exists to hold, not for a violation it carries.",
		},
	)
}

// checkFileLength enforces the manifesto's 500-line limit on hand-written
// Go. The two lists it passes make opposite promises - see their
// declarations above - and keeping them apart is what lets the waiver
// list function as a burndown rather than a permanent carve-out.
func checkFileLength() error {
	return magelib.CheckFileLength(fileLengthWaivers, fileLengthSkips...)
}

// checkLedger gates the divergence ledger's STRUCTURE, not its content.
//
// The ledger is this project's honesty layer and nothing checked its
// shape: `jq -e .` proves each line is JSON and says nothing about which
// keys it carries. Two entries were filed without an `opened` date and
// nothing noticed until one was rendered by hand to read it.
func checkLedger() error {
	if err := magelib.CheckDivergence("divergence.jsonl"); err != nil {
		return err
	}
	return magelib.CheckDeprecation("deprecation.jsonl")
}

// Python namespace for python-related tasks
type Python mg.Namespace

// Build builds the Python bindings (replaces Makefile)
func (Python) Build() error {
	mg.Deps(checkHermeticPython)
	fmt.Println("Building Python ADK bindings...")

	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	nativeDir := filepath.Join(cwd, "adk/python/gapi/native")

	// Create native directory if it doesn't exist (though gopy gen should verify path)
	if err := os.MkdirAll(nativeDir, 0755); err != nil {
		return err
	}

	// 1. gopy gen
	// gopy gen -no-make -vm=python3 -output=adk/python/gapi/native github.com/goppydae/gapi/adk/go
	fmt.Println("Running gopy gen...")
	if err := sh.Run("gopy", "gen", "-no-make", "-vm=python3", "-output=adk/python/gapi/native", "github.com/goppydae/gapi/adk/go"); err != nil {
		return fmt.Errorf("gopy gen failed: %w", err)
	}

	// Change to native directory for subsequent commands to match Makefile behavior
	// or use absolute paths. Makefile runs inside the dir. Let's act on files directly.

	// 2. goimports
	fmt.Println("Running goimports...")
	if err := sh.Run("goimports", "-w", filepath.Join(nativeDir, "adk.go")); err != nil {
		return fmt.Errorf("goimports failed: %w", err)
	}

	// 3. go build -buildmode=c-shared
	fmt.Println("Building adk_go.so...")
	// Note: We build inside the native dir to keep files together or specify output
	// Makefile: $(GOBUILD) -buildmode=c-shared -o adk_go$(LIBEXT) adk.go
	// We need to run this command *in* the native directory because it compiles the generated adk.go
	// which depends on imports.

	// No -mod flag: it is illegal in workspace mode (go.work), so hardcoding
	// -mod=mod made this target fail in the dev shell and pass in CI only
	// because CI sets GOWORK=off globally. The default (readonly) is correct
	// in both modes; go.work resolves the sibling modules in the dev shell.
	buildCmd := exec.Command("go", "build", "-buildmode=c-shared", "-o", "adk_go.so", "adk.go")
	buildCmd.Dir = nativeDir
	buildCmd.Stdout = os.Stdout
	buildCmd.Stderr = os.Stderr
	if err := buildCmd.Run(); err != nil {
		return fmt.Errorf("go build failed: %w", err)
	}

	// 4. python build.py
	fmt.Println("Running python build.py...")
	pyCmd := exec.Command("python3", "build.py")
	pyCmd.Dir = nativeDir
	pyCmd.Stdout = os.Stdout
	pyCmd.Stderr = os.Stderr
	if err := pyCmd.Run(); err != nil {
		// Try fallback to known nix path if "python3" generic fails (unlikely in nix shell but safe)
		return fmt.Errorf("python build.py failed: %w", err)
	}

	// 5. gcc link
	fmt.Println("Linking _adk.so...")
	// Gather python flags
	cflags, err := sh.Output("python3-config", "--cflags")
	if err != nil {
		return fmt.Errorf("failed to get python cflags: %w", err)
	}
	ldflags, err := sh.Output("python3-config", "--ldflags", "--embed")
	if err != nil {
		return fmt.Errorf("failed to get python ldflags: %w", err)
	}

	// NO SHELL. This used to build one string and hand it to `sh -c`,
	// because python3-config returns several space-separated flags and
	// that was the easy way to pass them. The shell then expanded
	// $ORIGIN in -Wl,-rpath,$ORIGIN as an undefined variable, so gcc
	// received -Wl,-rpath, and the extension shipped an EMPTY rpath
	// entry instead of the ecosystem manifesto's load-bearing one
	// (GAPI-DIV-098). Splitting the flags here and exec'ing gcc
	// directly removes the interpolation, and with it the whole class:
	// nothing between this line and the linker can reinterpret an
	// argument.
	//
	// -std=gnu17: gopy-generated C assumes the pre-C23 'bool'; see the
	// CGO_CFLAGS pin in the shell hook.
	linkArgs := []string{"-std=gnu17", "adk.c", "adk_go.so", "-o", "_adk.so"}
	linkArgs = append(linkArgs, strings.Fields(cflags)...)
	linkArgs = append(linkArgs, strings.Fields(ldflags)...)
	linkArgs = append(linkArgs, "-fPIC", "--shared", "-w", "-Wl,-rpath,$ORIGIN")

	linkCmd := exec.Command("gcc", linkArgs...)
	linkCmd.Dir = nativeDir
	linkCmd.Stdout = os.Stdout
	linkCmd.Stderr = os.Stderr
	if err := linkCmd.Run(); err != nil {
		return fmt.Errorf("gcc link failed: %w", err)
	}

	if err := assertOriginRunpath(filepath.Join(nativeDir, "_adk.so")); err != nil {
		return err
	}

	fmt.Println("Python bindings built successfully")
	return nil
}

// assertOriginRunpath fails unless the linked extension carries $ORIGIN in
// its RUNPATH or RPATH.
//
// THE INVARIANT WAS PRESENT IN THE COMMAND AND ABSENT FROM THE ARTIFACT
// for as long as anyone had looked, so this checks the artifact. It reads
// the ELF with the standard library rather than shelling out to patchelf
// or readelf: a gate that needs a tool the build does not already require
// is a gate that gets skipped on the machine where it matters.
//
// Why it is load-bearing at all: _adk.so links adk_go.so by bare soname,
// so the loader must find it beside the extension. The build appeared to
// work without it only because gopy's generated adk.py chdirs the process
// into the native directory around the import, which the empty rpath
// entry then resolved as the current directory. That is not a mechanism
// this repo controls, and Nix's fixupPhase strips the empty entry while
// preserving $ORIGIN - so packaging the extension needs the real thing.
func assertOriginRunpath(path string) error {
	f, err := elf.Open(path)
	if err != nil {
		return fmt.Errorf("read linked extension: %w", err)
	}
	defer func() { _ = f.Close() }()

	var found []string
	for _, tag := range []elf.DynTag{elf.DT_RUNPATH, elf.DT_RPATH} {
		vals, err := f.DynString(tag)
		if err != nil {
			continue
		}
		found = append(found, vals...)
		for _, v := range vals {
			for _, entry := range strings.Split(v, ":") {
				if strings.Contains(entry, "$ORIGIN") {
					return nil
				}
			}
		}
	}

	return fmt.Errorf("%s carries no $ORIGIN run path (found %q): the extension "+
		"links adk_go.so by soname and will not find it once the build "+
		"directory is not the working directory", filepath.Base(path), found)
}
