site_name: GAPI
site_description: GoPPydae Agent Process Infrastructure
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: purple
    - scheme: slate
      primary: teal
      accent: purple

nav:
  - Home: index.md
  - Starting:
    - Getting Started: getting-started.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Configuration Examples: config-example.md
  - Design:
    - Library Usage: library_usage.md
  - Agents:
    - Agent Examples: agent-examples.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
