site_name: GAPI
site_description: GoPPydae Agent Programming Interface
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: purple
    - scheme: slate
      primary: teal
      accent: purple

nav:
  - Home: index.md
  - Starting:
    - Getting Started: getting-started.md
    - Installation: installation.md
    - Configuration: configuration.md
  - Design:
    - Architecture: gapi-design-document.md
    - Features: features.md
    - Library Usage: library_usage.md
  - Development:
    - Developer Guide: development.md
    - Agent Examples: agent-examples.md
    - Lore: lore.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
