// Copyright (c) 2025 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

package docsgen_test

import (
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/spf13/cobra"

	"github.com/goppydae/gapi/pkg/docsgen"
)

// probeRoot builds a synthetic tree with the shape that matters here:
// nested subcommands, local flags, and a persistent flag on the root.
//
// The leaves carry a Run, and that is load-bearing rather than
// decorative. cobra renders only commands where IsAvailableCommand() is
// true, and a command is unavailable when it is neither runnable nor the
// parent of something runnable. A fixture built from bare Use/Short
// pairs therefore renders exactly one page - the root - and the
// generator looks broken when it is behaving correctly. The same rule
// applies to the real trees: a group command whose children all lose
// their Run would silently drop out of the reference.
func probeRoot() *cobra.Command {
	noop := func(*cobra.Command, []string) {}

	root := &cobra.Command{Use: "probectl", Short: "Probe control CLI"}
	root.PersistentFlags().String("control-addr", "", "Control address")

	agent := &cobra.Command{Use: "agent", Short: "Agent operations"}
	build := &cobra.Command{
		Use:   "build",
		Short: "Build an agent",
		Long:  "Builds an agent from source.",
		Run:   noop,
	}
	build.Flags().Bool("cgo", false, "Enable cgo")
	agent.AddCommand(build)

	root.AddCommand(agent)
	root.AddCommand(&cobra.Command{Use: "ping", Short: "Ping the daemon", Run: noop})
	return root
}

func renderedFiles(t *testing.T, dir string) []string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	var out []string
	for _, e := range entries {
		out = append(out, e.Name())
	}
	sort.Strings(out)
	return out
}

func TestCLI_RendersEveryCommandInTheTree(t *testing.T) {
	dir := t.TempDir()
	if err := docsgen.CLI(probeRoot(), dir); err != nil {
		t.Fatalf("CLI: %v", err)
	}
	want := []string{
		"probectl.md",
		"probectl_agent.md",
		"probectl_agent_build.md",
		"probectl_ping.md",
	}
	got := renderedFiles(t, dir)
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("rendered %v, want %v", got, want)
	}
}

func TestCLI_WritesRelearnFrontMatterWithTheCommandPath(t *testing.T) {
	dir := t.TempDir()
	if err := docsgen.CLI(probeRoot(), dir); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(filepath.Join(dir, "probectl_agent_build.md"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(body)
	if !strings.HasPrefix(s, "---\n") {
		t.Error("page does not start with front matter")
	}
	if !strings.Contains(s, `title: "probectl agent build"`) {
		t.Errorf("front matter title is not the command path:\n%s", firstLine(s))
	}
	if !strings.Contains(s, "--cgo") {
		t.Error("the command's own flag is missing from its page")
	}
}

// THE TRAP THE WHOLE DRIFT GATE TURNS ON. Cobra stamps a generated-on
// date unless DisableAutoGenTag is set, and it must be set on every
// command rather than the root, because each is constructed separately
// and carries its own zero value.
func TestCLI_CarriesNoGeneratedOnDate(t *testing.T) {
	dir := t.TempDir()
	if err := docsgen.CLI(probeRoot(), dir); err != nil {
		t.Fatal(err)
	}
	year := strconv.Itoa(time.Now().Year())
	for _, name := range renderedFiles(t, dir) {
		body, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatal(err)
		}
		s := string(body)
		if strings.Contains(s, "Auto generated by spf13/cobra") {
			t.Errorf("%s carries cobra's auto-generated tag, which contains a date", name)
		}
		if strings.Contains(s, year) {
			t.Errorf("%s contains the current year, so the page is a function of the clock", name)
		}
	}
}

func TestCLI_IsDeterministic(t *testing.T) {
	a, b := t.TempDir(), t.TempDir()
	if err := docsgen.CLI(probeRoot(), a); err != nil {
		t.Fatal(err)
	}
	if err := docsgen.CLI(probeRoot(), b); err != nil {
		t.Fatal(err)
	}
	for _, name := range renderedFiles(t, a) {
		x, err := os.ReadFile(filepath.Join(a, name))
		if err != nil {
			t.Fatal(err)
		}
		y, err := os.ReadFile(filepath.Join(b, name))
		if err != nil {
			t.Fatal(err)
		}
		if string(x) != string(y) {
			t.Errorf("%s differs between two renders of one tree", name)
		}
	}
}

func TestCLI_RejectsANilRoot(t *testing.T) {
	if err := docsgen.CLI(nil, t.TempDir()); err == nil {
		t.Fatal("a nil root must be refused rather than producing an empty reference")
	}
}

func TestMan_RendersOnePagePerCommand(t *testing.T) {
	dir := t.TempDir()
	if err := docsgen.Man(probeRoot(), dir, "0.1.0-proto2k"); err != nil {
		t.Fatalf("Man: %v", err)
	}
	want := []string{"probectl-agent-build.1", "probectl-agent.1", "probectl-ping.1", "probectl.1"}
	got := renderedFiles(t, dir)
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("rendered %v, want %v", got, want)
	}
}

// GenManHeader stamps time.Now() when Date is nil, which makes every
// regeneration produce different bytes and reads, under a byte-comparing
// gate, as "the CLI changed" on a tree where nothing changed.
func TestMan_CarriesTheInjectedVersionAndNoClock(t *testing.T) {
	dir := t.TempDir()
	if err := docsgen.Man(probeRoot(), dir, "0.1.0-proto2k"); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(filepath.Join(dir, "probectl.1"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(body)
	if !strings.Contains(s, "0.1.0-proto2k") {
		t.Errorf("man page does not name the injected version:\n%s", firstLine(s))
	}
	if strings.Contains(s, strconv.Itoa(time.Now().Year())) {
		t.Errorf("man page contains the current year, so it is a function of the clock:\n%s", firstLine(s))
	}
}

func TestMan_RefusesAnEmptyVersion(t *testing.T) {
	if err := docsgen.Man(probeRoot(), t.TempDir(), ""); err == nil {
		t.Fatal("an empty version must be refused; cobra would stamp the clock instead")
	}
}

func TestMan_IsDeterministic(t *testing.T) {
	a, b := t.TempDir(), t.TempDir()
	if err := docsgen.Man(probeRoot(), a, "1.0.0"); err != nil {
		t.Fatal(err)
	}
	if err := docsgen.Man(probeRoot(), b, "1.0.0"); err != nil {
		t.Fatal(err)
	}
	for _, name := range renderedFiles(t, a) {
		x, _ := os.ReadFile(filepath.Join(a, name))
		y, _ := os.ReadFile(filepath.Join(b, name))
		if string(x) != string(y) {
			t.Errorf("%s differs between two renders of one tree", name)
		}
	}
}

// Section 7 is the one written page. It goes through go-md2man, which is
// vendored for cobra's man generator anyway, which is what lets pandoc
// leave the flakes.
func TestOverview_ConvertsMarkdownAndDropsFrontMatter(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "overview.md")
	out := filepath.Join(dir, "probe.7")
	page := "---\ntitle: \"Overview\"\n---\n\n# Probe\n\nProbe supervises agents.\n"
	if err := os.WriteFile(src, []byte(page), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := docsgen.Overview(src, out, "probe", "1.0.0"); err != nil {
		t.Fatalf("Overview: %v", err)
	}
	body, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	s := string(body)
	if !strings.HasPrefix(s, `.TH PROBE 7 "1.0.0"`) {
		t.Errorf("section 7 header is wrong:\n%s", firstLine(s))
	}
	if !strings.Contains(s, "Probe supervises agents.") {
		t.Error("the page body did not survive conversion")
	}
	if strings.Contains(s, "title:") {
		t.Error("Hugo front matter leaked into the roff output")
	}
}
