
# python wrapper for package github.com/goppydae/gapi/adk/go within overall package adk
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy build -output=adk/python/gapi/native -vm=python3 github.com/goppydae/gapi/adk/go

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _adk
from . import go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from adk import adk
# and then refer to everything using adk. prefix
# packages imported by this package listed below:




# ---- Types ---


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---


# ---- Interfaces ---


# ---- Structs ---


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---


# ---- Functions ---
def InjectCommand(cmd, goRun=False):
	"""InjectCommand(str cmd) 
	
	InjectCommand is a helper for testing/simulation to push a command into the mailbox.
	"""
	_adk.adk_InjectCommand(cmd, goRun)
def SendEvent(jsonStr, goRun=False):
	"""SendEvent(str jsonStr) 
	
	SendEvent sends a raw JSON event string to the supervisor.
	"""
	_adk.adk_SendEvent(jsonStr, goRun)
def AwaitCommand():
	"""AwaitCommand() str
	
	AwaitCommand blocks until a command is received from the supervisor.
	Returns the command string (e.g. "start", "stop").
	In a real implementation, this would read from a QUIC stream or IPC socket.
	"""
	return _adk.adk_AwaitCommand()
def Initialize(name, version, typeStr, goRun=False):
	"""Initialize(str name, str version, str typeStr) 
	
	Initialize sets up the agent identity.
	"""
	_adk.adk_Initialize(name, version, typeStr, goRun)


