.nh
.TH "gapictl" "1" "Jan 1970" "gapictl 0.1.0-proto2m" "General Commands Manual"

.SH NAME
gapictl - Supervision kernel control CLI


.SH SYNOPSIS
\fBgapictl [flags]\fP


.SH DESCRIPTION
Supervision kernel control CLI


.SH OPTIONS
\fB--control-addr\fP=""
	Address of the target daemon's control plane (empty: from config)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for gapictl

.PP
\fB--log-level\fP=""
	Log level: debug, info, warn, error

.PP
\fB--tls-ca\fP=""
	CA certificate used to verify the daemon

.PP
\fB--tls-insecure\fP[=false]
	Skip verification (INSECURE)

.PP
\fB-v\fP, \fB--version\fP[=false]
	version for gapictl


.SH SEE ALSO
\fBgapictl-agent(1)\fP, \fBgapictl-crypto(1)\fP, \fBgapictl-lifecycle(1)\fP, \fBgapictl-ping(1)\fP, \fBgapictl-shutdown(1)\fP, \fBgapictl-tui(1)\fP, \fBgapictl-version(1)\fP
